import '../css/Availability.css'; 
import { useState } from "react";

function CreateSchedule() {
  const [type, setType] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [holidaysOff, setHolidaysOff] = useState([]);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // simple comma-separated input for shift IDs
  const [shifts, setShifts] = useState('');

  const handleHolidayChange = (e) => {
    const value = e.target.value;
    setHolidaysOff(value.split(',').map(date => date.trim()));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const payload = {
      type,
      startDate,
      endDate,
      shifts: shifts.split(',').map(id => id.trim()), // convert to array
      holidaysOff,
      autoGenerated,
    };

    try {
      const res = await fetch("/api/schedules", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      const data = await res.json();
      if (data.success) {
        alert("Schedule created successfully!");
      } else {
        alert(`Error: ${data.message}`);
      }
    } catch (err) {
      console.error("Error creating schedule:", err);
    }
  };

  return (
    <div className="availability-container">
      <h2>Create New Schedule</h2>
      <form onSubmit={handleSubmit}>

        <div className="name-field">
          <label>
            Type:
            <input 
              type="text" 
              value={type} 
              onChange={e => setType(e.target.value)} 
              required 
            />
          </label>
        </div>

        <div className="name-field">
          <label>
            Start Date:
            <input 
              type="date" 
              value={startDate} 
              onChange={e => setStartDate(e.target.value)} 
              required 
            />
          </label>
        </div>

        <div className="name-field">
          <label>
            End Date:
            <input 
              type="date" 
              value={endDate} 
              onChange={e => setEndDate(e.target.value)} 
              required 
            />
          </label>
        </div>

        <div className="name-field">
          <label>
            Shift IDs (comma separated):
            <input 
              type="text" 
              value={shifts} 
              onChange={e => setShifts(e.target.value)} 
            />
          </label>
        </div>

        <div className="name-field">
          <label>
            Holidays Off (comma separated, YYYY-MM-DD):
            <input 
              type="text" 
              value={holidaysOff.join(', ')} 
              onChange={handleHolidayChange} 
            />
          </label>
        </div>

        <div className="name-field">
          <label>
            Auto Generate?{" "}
            <input 
              type="checkbox" 
              checked={autoGenerated} 
              onChange={e => setAutoGenerated(e.target.checked)} 
            />
          </label>
        </div>

        <input type="submit" value="Create Schedule" />
      </form>
    </div>
  );
}

export default CreateSchedule;
