import { useState, useEffect } from 'react';
import './ViewSchedules.css';

function ViewSchedules() {
  const [schedules, setSchedules] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchSchedules();
  }, []);

  const fetchSchedules = async () => {
    try {
      setLoading(true);
      setError(null);
      
      console.log('Fetching schedules from API...');
      const response = await fetch('http://localhost:5002/api/schedules', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });
      
      console.log('Response status:', response.status);
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const data = await response.json();
      console.log('API response:', data);
      
      if (data.success) {
        setSchedules(data.data || []);
        console.log(`Loaded ${data.data?.length || 0} schedules`);
      } else {
        setError(data.message || 'Failed to fetch schedules');
      }
    } catch (err) {
      console.error('Error fetching schedules:', err);
      setError('Error fetching schedules: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const formatTime = (dateString) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });
  };

  if (loading) {
    return (
      <div className="view-schedules-container">
        <h1>View Schedules</h1>
        <div className="loading">Loading schedules...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="view-schedules-container">
        <h1>View Schedules</h1>
        <div className="error">{error}</div>
        <button onClick={fetchSchedules} className="retry-btn">Retry</button>
      </div>
    );
  }

  return (
    <div className="view-schedules-container">
      <h1>View Schedules</h1>
      
      {schedules.length === 0 ? (
        <div className="no-schedules">
          <p>No schedules found. Create your first schedule to get started!</p>
        </div>
      ) : (
        <div className="schedules-grid">
          {schedules.map((schedule) => (
            <div key={schedule._id} className="schedule-card">
              <div className="schedule-header">
                <h3>{schedule.type.charAt(0).toUpperCase() + schedule.type.slice(1)} Schedule</h3>
                <span className={`schedule-type ${schedule.autoGenerated ? 'auto-generated' : 'manual'}`}>
                  {schedule.autoGenerated ? 'Auto-Generated' : 'Manual'}
                </span>
              </div>
              
              <div className="schedule-dates">
                <p><strong>Start:</strong> {formatDate(schedule.startDate)}</p>
                <p><strong>End:</strong> {formatDate(schedule.endDate)}</p>
              </div>

              {schedule.holidaysOff && schedule.holidaysOff.length > 0 && (
                <div className="holidays-off">
                  <h4>Holidays Off:</h4>
                  <ul>
                    {schedule.holidaysOff.map((holiday, index) => (
                      <li key={index}>{formatDate(holiday)}</li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="shifts-section">
                <h4>Shifts ({schedule.shifts.length})</h4>
                {schedule.shifts.length === 0 ? (
                  <p className="no-shifts">No shifts assigned to this schedule</p>
                ) : (
                  <div className="shifts-list">
                    {schedule.shifts.map((shift) => (
                      <div key={shift._id} className="shift-item">
                        <div className="shift-time">
                          <span>{formatTime(shift.startTime)} - {formatTime(shift.endTime)}</span>
                        </div>
                        <div className="shift-workers">
                          {shift.worker && shift.worker.length > 0 ? (
                            <div>
                              <strong>Workers:</strong>
                              <ul>
                                {shift.worker.map((worker) => (
                                  <li key={worker._id}>
                                    {worker.name || worker.email || 'Unknown Worker'}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          ) : (
                            <span className="no-workers">No workers assigned</span>
                          )}
                        </div>
                        {shift.notes && (
                          <div className="shift-notes">
                            <strong>Notes:</strong> {shift.notes}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default ViewSchedules;
