import mongoose from "mongoose";


const scheduleSchema = new mongoose.Schema({
  type: { type: String, enum: ["week", "month"], required: true },
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },

  shifts: [{ type: mongoose.Schema.Types.ObjectId, ref: "Shift" }], 

  // Track which days are off globally
  holidaysOff: [{ type: Date }],

  // Was this schedule auto-generated?
  autoGenerated: { type: Boolean, default: false },
}, { timestamps: true });


const Schedule = mongoose.model("Schedule", scheduleSchema);

export { Schedule };